######################################################################
##
## Filename: Control_unit.udo
## Created on: Fri Dec 15 5:46:18 PM Eastern Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
